--- # Виды закупаемой продукции
- { ref_id: 61001, position: 01, name: "ПИР", fullname: "Проектно-изыскательные работы" }
- { ref_id: 61002, position: 02, name: "ГЭ", fullname: "Прохождение экспертизы проектов" }
- { ref_id: 61003, position: 03, name: "АН", fullname: "Авторский надзор за ходом строительства" }
- { ref_id: 61004, position: 04, name: "ТН", fullname: "Технический надзор" }
- { ref_id: 61005, position: 05, name: "СМР", fullname: "Строительно-монтажные работы" }
- { ref_id: 61006, position: 06, name: "ПНР", fullname: "Пуско-наладочные работы" }
- { ref_id: 61007, position: 07, name: "ГП", fullname: "Генподрядные работы" }
- { ref_id: 61008, position: 08, name: "УС", fullname: "Услуги сторонних организаций по управлению строительством" }
- { ref_id: 61009, position: 09, name: "МТРиО", fullname: "Поставка материально-технических ресурсов и оборудования" }
- { ref_id: 61010, position: 10, name: "ОН", fullname: "Приобретение, аренда недвижимости" }
- { ref_id: 61011, position: 11, name: "ИТ", fullname: "Приобретение и тех. обслуживание вычислительной и оргтехники, внедрение и сопровождение лицензионного ПО, КИС" }
- { ref_id: 61012, position: 12, name: "ТС", fullname: "Покупка, аренда транспортных средств и спецтехники, транспортные услуги" }
- { ref_id: 61013, position: 13, name: "СБ", fullname: "Обеспечение безопасности и защита коммерческой, промышленной, финансовой, деловой и другой информации" }
- { ref_id: 61014, position: 14, name: "ФО", fullname: "Отбор финансоых организаций в соответствии со статьей 18 №135-ФЗ о защите конкуренции" }
- { ref_id: 61015, position: 15, name: "Охрана", fullname: "Услуги сторонних организаций по охране имущества" }
- { ref_id: 61016, position: 16, name: "Услуги", fullname: "Прочие услуги" }
- { ref_id: 61017, position: 17, name: "Работы", fullname: "Прочие работы" }
